spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**
        - id: products-service
          uri: http://localhost:8083
          predicates:
            - Path=/products/**
        - id: shipping-service
          uri: http://localhost:8084
          predicates:
            - Path=/shipping/**
        - id: warehouse-service
          uri: http://localhost:8085
          predicates:
            - Path=/warehouse/**
        - id: analytics-service
          uri: http://localhost:8086
          predicates:
            - Path=/analytics/**
