server:
  port: 8084

spring:
  application:
    name: warehouse-service
  datasource:
    url: jdbc:postgresql://postgres-warehouse:5432/warehouse_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  product-service:
    host: products-service
    port: 9090
  client:
    products-service:
      address: static://products-service:9090
      negotiation-type: plaintext
  server:
    port: 9094

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: warehouse-service
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    auto-offset-reset: latest
  producer:
    group-id: warehouse-service
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    auto-offset-reset: latest

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true