server:
  port: 8086

spring:
  application:
    name: analytics-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: analytics_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true